%YAML:1.0

drone_id_and_uwb_ext:
  - id: 0
    is_lidar: 0
    uwb_ext: [0.0, 0.0, 0.0]
  - id: 1
    is_lidar: 0
    uwb_ext: [0.0, 0.0, 0.0]
  - id: 2
    is_lidar: 0
    uwb_ext: [0.0, 0.0, 0.0]
  - id: 3
    is_lidar: 0
    uwb_ext: [0.0, 0.0, 0.0]
  - id: 4
    is_lidar: 0
    uwb_ext: [0.0, 0.0, 0.0]
  - id: 5
    is_lidar: 0
    uwb_ext: [0.0, 0.0, 0.0]
  - id: 6
    is_lidar: 1
    uwb_ext: [0.0, 0.0, 0.0]
  - id: 7
    is_lidar: 1
    uwb_ext: [0.0, 0.0, 0.0]

uwb_bias: 0.25
consider_uwb_extrinsic: 0
uwb_anchor_id_and_position:
  - id: 25
    position: [25.0, 25.0, 25.0]
  - id: 52
    position: [52.0, 52.0, 52.0]

revised_odom_topic: "revised_odom"

swarm_odom_topic: "/others_odom"
swarm_odom_gt_topic: "/others_odom_gt"
swarm_odom_freq: 3.0

distance_measurement_topic: "/distance_meas"
distance_measurement_freq: 3.0

enable_bearing: 0
bearing_measurement_topic: "/bearing_meas"
bearing_measurement_freq: 2.0

drift_from_center_topic: "/drift_from_center"
drift_to_edges_topic: "/drift_to_edges"
drift_gt_topic: "/drift_gt"

# Debug topics
swarm_dist_est_topic: "/debug_distance_est"
swarm_dist_meas_topic: "/debug_distance_meas"
swarm_bearing_diff_topic: "/debug_bearing_diff"
swarm_bearing_diff_before_opt_topic: "/debug_bearing_diff_before_opt"

optimize_z: 0
optimize_yaw: 0
sliding_window_length: 6                   # In seconds
optimize_per_N_meas: 3

prior_cost_weight: 0.0
regularization_cost_weight: 0.01
distance_cost_weight: 3.0
bearing_cost_weight: 10.0

distance_outlier_threshold: 1.0
max_deanonymization_bearing_angle: 45.0    # In degrees
huber_threshold: 1.0

ceres_verbosity_level: 0                   # 0: Silent  1: Quiet    2: Verbose
glog_severity_level: 0                     # 0: Info    1: Warning  2: Error    3: Fatal
publish_debug_topics: 1
custom_debug_output: 0